package com.example.osmu.admin;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public record DashboardOperationsEvidenceHandoffResponse(
        String result,
        String generatedAt,
        DashboardOperationsEvidenceHandoffNextStepResponse nextStep,
        DashboardOperationsEvidenceHandoffNextStepResponse currentBottleneck,
        int stageCount,
        int readyStageCount,
        String readinessSummary,
        int readinessPassedCount,
        int readinessPendingCount,
        int readinessTotalCount,
        int readinessCheckCount,
        String dispatchPreflightResult,
        String dispatchGithubRepository,
        int readyDispatchTemplateCount,
        int blockedDispatchTemplateCount,
        List<Integer> readyDispatchActionOrders,
        List<Integer> blockedDispatchActionOrders,
        List<Integer> invocationSelectedActionOrders,
        List<Integer> dispatchPreflightSelectedActionOrders,
        List<Integer> workflowRunIdPlanActionOrders,
        List<Integer> artifactCollectionActionOrders,
        boolean dispatchPreflightScopeMismatch,
        boolean workflowRunIdPlanStale,
        boolean workflowRunIdPlanScopeMismatch,
        boolean artifactCollectionStale,
        boolean artifactCollectionScopeMismatch,
        List<DashboardOperationsEvidenceHandoffDispatchWorkflowResponse> readyDispatchWorkflows,
        List<DashboardOperationsEvidenceHandoffDispatchWorkflowResponse> blockedDispatchWorkflows,
        int browserDispatchChecklistCount,
        List<DashboardOperationsEvidenceHandoffBrowserDispatchChecklistResponse> browserDispatchChecklist,
        int securityEvidenceFinalizerRunIdInputHintCount,
        List<DashboardOperationsWorkflowRunIdInputResponse> securityEvidenceFinalizerRunIdInputHints,
        int staleReportCount,
        int blockedActionCount,
        int missingWorkflowRunCount,
        int missingRequiredArtifactCount,
        int failedImportCount,
        int finalizerFailedCount,
        int finalizerGapCount,
        List<DashboardOperationsEvidenceHandoffPostDispatchCommandResponse> postDispatchCommands,
        List<DashboardOperationsEvidenceHandoffStageResponse> stages
) {
    public static DashboardOperationsEvidenceHandoffResponse empty() {
        return new DashboardOperationsEvidenceHandoffResponse(
                "",
                "",
                DashboardOperationsEvidenceHandoffNextStepResponse.empty(),
                DashboardOperationsEvidenceHandoffNextStepResponse.empty(),
                0,
                0,
                "",
                0,
                0,
                0,
                0,
                "",
                "",
                0,
                0,
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                false,
                false,
                false,
                false,
                false,
                List.of(),
                List.of(),
                0,
                List.of(),
                0,
                List.of(),
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                List.of(),
                List.of()
        );
    }
}
