package com.example.osmu.admin;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public record DashboardOperationsReadinessConvergenceResponse(
        String result,
        String generatedAt,
        String handoffReportPath,
        String readinessReportPath,
        String operationsReadinessFinalizeReportPath,
        boolean handoffExists,
        String handoffResult,
        boolean handoffStale,
        String handoffTimestamp,
        String handoffTimestampSource,
        String readinessTimestamp,
        String readinessTimestampSource,
        boolean readinessExists,
        String readinessResult,
        String readinessSummary,
        int readinessPassedCount,
        int readinessPendingCount,
        int readinessTotalCount,
        int readinessCheckCount,
        boolean finalizerExists,
        String finalizerResult,
        String finalizerReadinessResult,
        int finalizerFailedCount,
        boolean finalizerFailedCountValid,
        String finalizerFailedCountRaw,
        String kubernetesOperationsReportSyncReportPath,
        boolean kubernetesReportSyncExists,
        String kubernetesReportSyncResult,
        boolean kubernetesReportSyncStale,
        String kubernetesReportSyncTimestamp,
        String kubernetesReportSyncTimestampSource,
        String kubernetesReportSyncFreshnessReason,
        int kubernetesReportSyncFailedCount,
        boolean kubernetesReportSyncFailedCountValid,
        String kubernetesReportSyncFailedCountRaw,
        String kubernetesReportSyncConfigMapName,
        String kubernetesReportSyncConfigMapKey,
        String kubernetesReportSyncSourceReportResult,
        String kubernetesReportSyncWorkflowCommand,
        String kubernetesReportSyncWorkflowNote,
        boolean kubernetesReportSyncReady,
        int finalizerGapCount,
        int stageCount,
        int readyStageCount,
        int blockedActionCount,
        boolean handoffInputFreeBlockedReviewReportExists,
        String handoffInputFreeBlockedReviewReportResult,
        String handoffInputFreeBlockedReviewReportGeneratedAt,
        int handoffInputFreeBlockedReviewReportSelectedActionCount,
        int handoffInputFreeBlockedReviewReportPlannedCount,
        int handoffInputFreeBlockedReviewReportBlockedCount,
        int handoffInputFreeBlockedReviewReportFailedCount,
        int handoffInputFreeBlockedReviewReportExecutedCount,
        List<Integer> handoffInputFreeBlockedReviewReportActionOrders,
        boolean handoffInputFreeBlockedReviewReportStale,
        boolean handoffInputFreeBlockedReviewReportScopeMismatch,
        String handoffOperatorInputValuesProfileReportPath,
        boolean handoffOperatorInputValuesProfileExists,
        String handoffOperatorInputValuesProfileResult,
        String handoffOperatorInputValuesProfileGeneratedAt,
        boolean handoffOperatorInputValuesProfileDefaultsUsed,
        boolean handoffOperatorInputValuesProfileDefaultsSkipped,
        String handoffOperatorInputValuesProfileDefaultsSkipReason,
        int handoffOperatorInputValuesProfileDefaultValueCount,
        int handoffOperatorInputValuesProfileFilledValueCount,
        int handoffOperatorInputValuesProfileBlankValueCount,
        String handoffOperatorInputValuesCheckResult,
        int handoffOperatorInputValuesCheckValueCount,
        int handoffOperatorInputValuesCheckReadyValueCount,
        int handoffOperatorInputValuesCheckMissingValueCount,
        int handoffOperatorInputValuesCheckUnsafeValueCount,
        int handoffOperatorInputValuesCheckInvalidValueCount,
        int handoffOperatorInputValuesCheckValueReadyActionCount,
        int handoffOperatorInputValuesCheckNonReadyActionCount,
        int handoffOperatorInputValuesCheckActionSummaryCount,
        List<Integer> handoffOperatorInputValuesCheckNonReadyActionOrders,
        List<DashboardOperationsInputValueActionSummaryResponse> handoffOperatorInputValuesCheckNonReadyActionSummaries,
        String handoffWorkflowRunIdPlanQueryMode,
        boolean handoffWorkflowRunIdPlanGithubApiTokenPresent,
        boolean handoffWorkflowRunIdPlanGithubApiUnauthenticated,
        boolean handoffWorkflowRunIdPlanQueryExecuted,
        int handoffWorkflowRunIdPlanQueryExecutedCount,
        int handoffWorkflowRunIdPlanQueryWorkflowCount,
        int handoffWorkflowRunIdPlanQuerySucceededCount,
        int handoffWorkflowRunIdPlanQueryErrorCount,
        int handoffWorkflowRunIdPlanCandidateCount,
        int missingWorkflowRunCount,
        int missingRequiredArtifactCount,
        int failedImportCount,
        DashboardOperationsReadinessConvergenceBottleneckResponse currentBottleneck,
        List<DashboardOperationsEvidenceHandoffPostDispatchCommandResponse> handoffPostDispatchCommands,
        List<String> handoffBrowserDispatchDependencyNotes,
        int handoffSecurityEvidenceFinalizerRunIdInputHintCount,
        List<DashboardOperationsWorkflowRunIdInputResponse> handoffSecurityEvidenceFinalizerRunIdInputHints,
        List<DashboardOperationsReadinessConvergenceCommandResponse> recommendedCommands,
        String decisionRule,
        String safetyPolicy
) {
    public static DashboardOperationsReadinessConvergenceResponse empty() {
        return new DashboardOperationsReadinessConvergenceResponse(
                "",
                "",
                "",
                "",
                "",
                false,
                "",
                false,
                "",
                "",
                "",
                "",
                false,
                "",
                "",
                0,
                0,
                0,
                0,
                false,
                "",
                "",
                0,
                false,
                "",
                "",
                false,
                "",
                false,
                "",
                "",
                "",
                0,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                false,
                0,
                0,
                0,
                0,
                false,
                "",
                "",
                0,
                0,
                0,
                0,
                0,
                List.of(),
                false,
                false,
                "",
                false,
                "",
                "",
                false,
                false,
                "",
                0,
                0,
                0,
                "",
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                List.of(),
                List.of(),
                "",
                false,
                false,
                false,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                DashboardOperationsReadinessConvergenceBottleneckResponse.empty(),
                List.of(),
                List.of(),
                0,
                List.of(),
                List.of(),
                "",
                ""
        );
    }
}