import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const homeViewSource = readFileSync(fileURLToPath(new URL('./HomeView.vue', import.meta.url)), 'utf8')

test('HomeView exposes stable selectors for browser E2E flows', () => {
  const requiredTestIds = [
    'status-list',
    'login-form',
    'login-id-input',
    'login-password-input',
    'login-submit-button',
    'refresh-button',
    'logout-button',
    'error-alert',
    'metrics-grid',
    'backup-status-panel',
    'bucket-panel',
    'bucket-create-form',
    'bucket-name-input',
    'bucket-quota-input',
    'bucket-owner-type-select',
    'bucket-create-button',
    'bucket-table',
    'bucket-sync-button',
    'bucket-delete-button',
    'object-panel',
    'object-filter-form',
    'object-prefix-input',
    'object-search-input',
    'object-tag-filter-input',
    'object-list-limit-select',
    'object-search-button',
    'object-upload-form',
    'object-key-input',
    'object-tags-input',
    'object-file-input',
    'object-upload-button',
    'object-upload-cancel-button',
    'object-upload-retry-button',
    'object-upload-progress',
    'object-table',
    'object-detail-button',
    'object-detail-panel',
    'object-share-link-button',
    'object-share-link-url',
    'object-share-link-password-input',
    'object-share-link-ip-allowlist-input',
    'object-share-link-panel',
    'object-share-link-cleanup-button',
    'object-share-policy-panel',
    'object-share-policy-form',
    'object-share-policy-require-password',
    'object-share-policy-require-ip',
    'object-share-policy-max-expiry',
    'object-share-policy-max-downloads',
    'object-share-policy-save-button',
    'object-share-analytics-panel',
    'object-share-analytics-refresh-button',
    'object-share-analytics-filter-form',
    'object-share-analytics-bucket-filter',
    'object-share-analytics-status-filter',
    'object-share-analytics-limit-filter',
    'object-share-analytics-metrics',
    'object-share-analytics-list',
    'bucket-lifecycle-panel',
    'bucket-tags-panel',
    'quota-policy-panel',
    'quota-policy-form',
    'quota-policy-target-type',
    'quota-policy-target-search',
    'quota-policy-target-id',
    'quota-policy-quota-input',
    'quota-policy-reason-input',
    'quota-policy-save-button',
    'quota-policy-cancel-edit-button',
    'quota-policy-edit-button',
    'quota-policy-history-list',
    'audit-panel',
    'audit-filter-form',
    'audit-event-type-input',
    'audit-actor-id-input',
    'audit-request-id-input',
    'audit-target-type-input',
    'audit-target-id-input',
    'audit-result-select',
    'audit-search-button',
    'audit-export-button',
    'audit-reset-button',
    'audit-list',
    'confirm-backdrop',
    'confirm-dialog',
    'confirm-cancel-button',
    'confirm-submit-button',
  ]

  for (const testId of requiredTestIds) {
    assert.match(homeViewSource, new RegExp(`data-testid="${testId}"`), `Missing data-testid="${testId}"`)
  }

  assert.match(homeViewSource, /:data-testid="`bucket-row-\$\{bucket\.name\}`"/)
})
