apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: osmu
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - storage-expansion-rbac.yaml
  - configmap.yaml
  - mariadb.yaml
  - minio.yaml
  - backup.yaml
  - ha.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
