apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-backend
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-backend
    app.kubernetes.io/part-of: osmu
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-frontend
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-frontend
    app.kubernetes.io/part-of: osmu
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-mariadb
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-mariadb
    app.kubernetes.io/part-of: osmu
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-minio
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-minio
    app.kubernetes.io/part-of: osmu
automountServiceAccountToken: false
