apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-storage-expansion-runner
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-storage-expansion-runner
    app.kubernetes.io/part-of: osmu
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osmu-storage-expansion-runner
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-storage-expansion-runner
    app.kubernetes.io/part-of: osmu
rules:
  - apiGroups:
      - minio.min.io
    resources:
      - tenants
    resourceNames:
      - osmu-minio
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
    resourceNames:
      - osmu-minio
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets/status
    resourceNames:
      - osmu-minio
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osmu-storage-expansion-runner
  namespace: osmu
  labels:
    app.kubernetes.io/name: osmu-storage-expansion-runner
    app.kubernetes.io/part-of: osmu
subjects:
  - kind: ServiceAccount
    name: osmu-storage-expansion-runner
    namespace: osmu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osmu-storage-expansion-runner
