param(
    [string] $LightweightWorkflowPath = ".\.github\workflows\prototype-ci.yml",
    [string] $DurableDockerWorkflowPath = ".\.github\workflows\durable-docker-ci.yml",
    [string] $RealS3ClientWorkflowPath = ".\.github\workflows\real-s3-client-ci.yml",
    [string] $ContainerSecurityWorkflowPath = ".\.github\workflows\container-security-ci.yml",
    [string] $SecurityEvidenceFinalizerWorkflowPath = ".\.github\workflows\security-evidence-finalizer-ci.yml",
    [string] $BrowserE2EWorkflowPath = ".\.github\workflows\browser-e2e-ci.yml",
    [string] $IamRbacFinalizerWorkflowPath = ".\.github\workflows\iam-rbac-finalizer-ci.yml",
    [string] $StorageExpansionFinalizerWorkflowPath = ".\.github\workflows\storage-expansion-finalizer-ci.yml",
    [string] $KubernetesHaDrReadinessWorkflowPath = ".\.github\workflows\kubernetes-ha-dr-readiness-ci.yml",
    [string] $KubernetesDrFinalizerWorkflowPath = ".\.github\workflows\kubernetes-dr-finalizer-ci.yml",
    [string] $KubernetesOperationsReportSyncWorkflowPath = ".\.github\workflows\kubernetes-operations-report-sync-ci.yml",
    [string] $OperationsReadinessFinalizerWorkflowPath = ".\.github\workflows\operations-readiness-finalizer-ci.yml",
    [string] $OperationsReadinessArtifactFinalizerWorkflowPath = ".\.github\workflows\operations-readiness-artifact-finalizer-ci.yml",
    [string] $ManualSecretRotationEvidenceWorkflowPath = ".\.github\workflows\manual-secret-rotation-evidence.yml",
    [string] $ManualCommercialIntegrationEvidenceWorkflowPath = ".\.github\workflows\manual-commercial-integration-evidence.yml",
    [string] $ManualCommercialApprovalEvidenceWorkflowPath = ".\.github\workflows\manual-commercial-approval-evidence.yml",
    [string] $ManualOperationsHandoffPackageWorkflowPath = ".\.github\workflows\manual-operations-handoff-package.yml",
    [string] $EnterpriseAuthSmokeWorkflowPath = ".\.github\workflows\enterprise-auth-smoke-ci.yml",
    [string] $BrowserE2ESpecPath = ".\osmu-frontend\e2e\lightweight-demo.spec.js",
    [string] $FrontendPackagePath = ".\osmu-frontend\package.json",
    [string] $PlaywrightConfigPath = ".\osmu-frontend\playwright.config.js"
)

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Resolve-ProjectPath($path) {
    if ([System.IO.Path]::IsPathRooted($path)) {
        return [System.IO.Path]::GetFullPath($path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $root $path))
}

function Assert-Contains([string] $content, [string] $expected, [string] $label) {
    if (-not $content.Contains($expected)) {
        throw "$label does not contain expected text: $expected"
    }
}

function Read-RequiredFile([string] $path, [string] $label) {
    $resolvedPath = Resolve-ProjectPath $path
    if (-not (Test-Path -LiteralPath $resolvedPath)) {
        throw "$label missing: $resolvedPath"
    }
    $content = Get-Content -Raw -LiteralPath $resolvedPath
    return [pscustomobject]@{
        Path = $resolvedPath
        Content = $content
    }
}

function Assert-NotContains([string] $content, [string] $unexpected, [string] $label) {
    if ($content.Contains($unexpected)) {
        throw "$label must not contain text: $unexpected"
    }
}

function Read-Workflow([string] $path, [string] $label) {
    $resolvedPath = Resolve-ProjectPath $path
    if (-not (Test-Path -LiteralPath $resolvedPath)) {
        throw "$label missing: $resolvedPath"
    }
    $content = Get-Content -Raw -LiteralPath $resolvedPath
    if ($content.Contains("`t")) {
        throw "Tabs are not allowed in $label`: $resolvedPath"
    }
    return [pscustomobject]@{
        Path = $resolvedPath
        Content = $content
    }
}

$lightweightWorkflow = Read-Workflow $LightweightWorkflowPath "Lightweight CI workflow"
$workflow = $lightweightWorkflow.Content

Assert-Contains $workflow "name: Prototype CI" "Lightweight CI workflow"
Assert-Contains $workflow "push:" "Lightweight CI workflow"
Assert-Contains $workflow "pull_request:" "Lightweight CI workflow"
Assert-Contains $workflow "workflow_dispatch:" "Lightweight CI workflow"
Assert-Contains $workflow "contents: read" "Lightweight CI workflow"
Assert-Contains $workflow "cancel-in-progress: true" "Lightweight CI workflow"
Assert-Contains $workflow "runs-on: windows-latest" "Lightweight CI workflow"
Assert-Contains $workflow "timeout-minutes: 30" "Lightweight CI workflow"
Assert-Contains $workflow "actions/checkout@v4" "Lightweight CI workflow"
Assert-Contains $workflow "actions/setup-java@v4" "Lightweight CI workflow"
Assert-Contains $workflow "distribution: temurin" "Lightweight CI workflow"
Assert-Contains $workflow 'java-version: "17"' "Lightweight CI workflow"
Assert-Contains $workflow "actions/setup-node@v4" "Lightweight CI workflow"
Assert-Contains $workflow 'node-version: "24"' "Lightweight CI workflow"
Assert-Contains $workflow "cache-dependency-path: osmu-frontend/package-lock.json" "Lightweight CI workflow"
Assert-Contains $workflow "working-directory: osmu-frontend" "Lightweight CI workflow"
Assert-Contains $workflow "run: npm ci" "Lightweight CI workflow"
Assert-Contains $workflow "run: .\scripts\verify-local.ps1 -SkipDocker" "Lightweight CI workflow"
Assert-NotContains $workflow "RunDockerIntegration" "Lightweight CI workflow"
Assert-NotContains $workflow "RequireDocker" "Lightweight CI workflow"

$durableWorkflow = Read-Workflow $DurableDockerWorkflowPath "Durable Docker CI workflow"
$dockerWorkflow = $durableWorkflow.Content

Assert-Contains $dockerWorkflow "name: Durable Docker CI" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "workflow_dispatch:" "Durable Docker CI workflow"
Assert-NotContains $dockerWorkflow "pull_request:" "Durable Docker CI workflow"
Assert-NotContains $dockerWorkflow "push:" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "contents: read" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "runs-on: ubuntu-latest" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "timeout-minutes: 75" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "actions/checkout@v4" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "actions/setup-java@v4" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "distribution: temurin" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow 'java-version: "17"' "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "actions/setup-node@v4" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow 'node-version: "24"' "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "cache-dependency-path: osmu-frontend/package-lock.json" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "working-directory: osmu-frontend" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "run: npm ci" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "npx playwright install --with-deps chromium" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "shell: pwsh" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "Finalize durable MVP demo" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "finalize-durable-mvp-demo.ps1 -EnvFile ./infra/local/.env -EnvExample ./infra/local/.env.example -ComposeFile ./infra/local/docker-compose.yml -S3Client docker-mc" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "actions/upload-artifact@v4" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "durable-demo-reports" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-durable-demo-gate.json" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-durable-demo-gate.md" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-durable-demo-preflight.json" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-durable-demo-preflight.md" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-durable-mvp-finalize.json" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-durable-mvp-finalize.md" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-demo-readiness.json" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-release.json" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-mvp-audit.md" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-release-decision.md" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow ".osmu-run/latest-release-notes.md" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "docker compose --env-file ./infra/local/.env.example -f ./infra/local/docker-compose.yml logs --no-color" "Durable Docker CI workflow"
Assert-Contains $dockerWorkflow "docker compose --env-file ./infra/local/.env.example -f ./infra/local/docker-compose.yml down -v --remove-orphans" "Durable Docker CI workflow"

$realS3Workflow = Read-Workflow $RealS3ClientWorkflowPath "Real S3 client CI workflow"
$s3Workflow = $realS3Workflow.Content

Assert-Contains $s3Workflow "name: Real S3 Client CI" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "workflow_dispatch:" "Real S3 client CI workflow"
Assert-NotContains $s3Workflow "pull_request:" "Real S3 client CI workflow"
Assert-NotContains $s3Workflow "push:" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "contents: read" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "runs-on: windows-latest" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "timeout-minutes: 45" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "actions/checkout@v4" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "actions/setup-java@v4" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "distribution: temurin" "Real S3 client CI workflow"
Assert-Contains $s3Workflow 'java-version: "17"' "Real S3 client CI workflow"
Assert-Contains $s3Workflow "actions/setup-node@v4" "Real S3 client CI workflow"
Assert-Contains $s3Workflow 'node-version: "24"' "Real S3 client CI workflow"
Assert-Contains $s3Workflow "cache-dependency-path: osmu-frontend/package-lock.json" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "working-directory: osmu-frontend" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "run: npm ci" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "Invoke-WebRequest -Uri `"https://dl.min.io/client/mc/release/windows-amd64/mc.exe`"" "Real S3 client CI workflow"
Assert-Contains $s3Workflow '$env:GITHUB_PATH' "Real S3 client CI workflow"
Assert-Contains $s3Workflow "run: .\scripts\start-local-prototype.ps1" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "run: .\scripts\verify-s3-client-smoke.ps1 -Client mc -RequireClient" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "Get-ChildItem .\.osmu-run -Filter *.log" "Real S3 client CI workflow"
Assert-Contains $s3Workflow "run: .\scripts\stop-local-prototype.ps1 -ForcePorts" "Real S3 client CI workflow"

$containerSecurityWorkflow = Read-Workflow $ContainerSecurityWorkflowPath "Container Security CI workflow"
$securityWorkflow = $containerSecurityWorkflow.Content

Assert-Contains $securityWorkflow "name: Container Security CI" "Container Security CI workflow"
Assert-Contains $securityWorkflow "workflow_dispatch:" "Container Security CI workflow"
Assert-NotContains $securityWorkflow "pull_request:" "Container Security CI workflow"
Assert-NotContains $securityWorkflow "push:" "Container Security CI workflow"
Assert-Contains $securityWorkflow "contents: read" "Container Security CI workflow"
Assert-Contains $securityWorkflow "runs-on: ubuntu-latest" "Container Security CI workflow"
Assert-Contains $securityWorkflow "timeout-minutes: 45" "Container Security CI workflow"
Assert-Contains $securityWorkflow "actions/checkout@v4" "Container Security CI workflow"
Assert-Contains $securityWorkflow 'BACKEND_IMAGE: osmu-backend:${{ github.sha }}' "Container Security CI workflow"
Assert-Contains $securityWorkflow 'FRONTEND_IMAGE: osmu-frontend:${{ github.sha }}' "Container Security CI workflow"
Assert-Contains $securityWorkflow 'docker build -t "$BACKEND_IMAGE" ./osmu-backend' "Container Security CI workflow"
Assert-Contains $securityWorkflow 'docker build -t "$FRONTEND_IMAGE" ./osmu-frontend' "Container Security CI workflow"
Assert-Contains $securityWorkflow "aquasec/trivy:latest image --exit-code 1 --severity CRITICAL,HIGH --ignore-unfixed" "Container Security CI workflow"
Assert-Contains $securityWorkflow "anchore/syft:latest" "Container Security CI workflow"
Assert-Contains $securityWorkflow "spdx-json=/out/backend.spdx.json" "Container Security CI workflow"
Assert-Contains $securityWorkflow "spdx-json=/out/frontend.spdx.json" "Container Security CI workflow"
Assert-Contains $securityWorkflow "Write container security evidence" "Container Security CI workflow"
Assert-Contains $securityWorkflow "./scripts/write-container-security-evidence.ps1" "Container Security CI workflow"
Assert-Contains $securityWorkflow "-BackendScanPassed" "Container Security CI workflow"
Assert-Contains $securityWorkflow "-FrontendScanPassed" "Container Security CI workflow"
Assert-Contains $securityWorkflow "-BackendSbomPath" "Container Security CI workflow"
Assert-Contains $securityWorkflow "-FrontendSbomPath" "Container Security CI workflow"
Assert-Contains $securityWorkflow "-FailIfNotPassed" "Container Security CI workflow"
Assert-Contains $securityWorkflow ".osmu-run/latest-container-security-evidence.json" "Container Security CI workflow"
Assert-Contains $securityWorkflow "actions/upload-artifact@v4" "Container Security CI workflow"
Assert-Contains $securityWorkflow "osmu-container-security-" "Container Security CI workflow"
Assert-Contains $securityWorkflow "if-no-files-found: error" "Container Security CI workflow"

$securityEvidenceFinalizerWorkflow = Read-Workflow $SecurityEvidenceFinalizerWorkflowPath "Security Evidence Finalizer CI workflow"
$securityEvidenceFinalizerWorkflowContent = $securityEvidenceFinalizerWorkflow.Content

Assert-Contains $securityEvidenceFinalizerWorkflowContent "name: Security Evidence Finalizer CI" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "workflow_dispatch:" "Security Evidence Finalizer CI workflow"
Assert-NotContains $securityEvidenceFinalizerWorkflowContent "pull_request:" "Security Evidence Finalizer CI workflow"
Assert-NotContains $securityEvidenceFinalizerWorkflowContent "push:" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "contents: read" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "actions: read" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "runs-on: ubuntu-latest" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "timeout-minutes: 25" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "image_signing_run_id:" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "image_signing_artifact_name:" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "container_security_run_id:" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "container_security_artifact_name:" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "actions/download-artifact@v4" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "github-token: `${{ secrets.GITHUB_TOKEN }}" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "Download image signing evidence" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "Download container security evidence" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "Validate downloaded evidence paths" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "Finalize security evidence" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "./scripts/finalize-security-evidence.ps1" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "-FailIfNotPassed" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent ".osmu-run/security-evidence-finalizer/source/image-signing/latest-image-signing-evidence.json" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent ".osmu-run/security-evidence-finalizer/source/container-security/latest-container-security-evidence.json" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent ".osmu-run/latest-security-evidence-finalize.json" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent ".osmu-run/latest-image-signing-evidence.json" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent ".osmu-run/latest-container-security-evidence.json" "Security Evidence Finalizer CI workflow"
Assert-Contains $securityEvidenceFinalizerWorkflowContent "security-evidence-finalizer-" "Security Evidence Finalizer CI workflow"

$browserWorkflow = Read-Workflow $BrowserE2EWorkflowPath "Browser E2E CI workflow"
$browserWorkflowContent = $browserWorkflow.Content

Assert-Contains $browserWorkflowContent "name: Browser E2E CI" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "workflow_dispatch:" "Browser E2E CI workflow"
Assert-NotContains $browserWorkflowContent "pull_request:" "Browser E2E CI workflow"
Assert-NotContains $browserWorkflowContent "push:" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "contents: read" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "runs-on: windows-latest" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "timeout-minutes: 45" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "actions/checkout@v4" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "actions/setup-java@v4" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "actions/setup-node@v4" "Browser E2E CI workflow"
Assert-NotContains $browserWorkflowContent "npm install --no-save @playwright/test" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "npx playwright install chromium" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "run: .\scripts\start-local-prototype.ps1" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "OSMU_FRONTEND_BASE_URL: http://localhost:5173" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "run: npm run test:e2e" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "Get-ChildItem .\.osmu-run -Filter *.log" "Browser E2E CI workflow"
Assert-Contains $browserWorkflowContent "run: .\scripts\stop-local-prototype.ps1 -ForcePorts" "Browser E2E CI workflow"

$iamRbacWorkflow = Read-Workflow $IamRbacFinalizerWorkflowPath "IAM/RBAC Finalizer CI workflow"
$iamRbacWorkflowContent = $iamRbacWorkflow.Content

Assert-Contains $iamRbacWorkflowContent "name: IAM RBAC Finalizer CI" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "workflow_dispatch:" "IAM/RBAC Finalizer CI workflow"
Assert-NotContains $iamRbacWorkflowContent "pull_request:" "IAM/RBAC Finalizer CI workflow"
Assert-NotContains $iamRbacWorkflowContent "push:" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "contents: read" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "runs-on: ubuntu-latest" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "timeout-minutes: 35" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "run_backend_policy_tests:" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "run_live:" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "run_kubernetes_live_auth:" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "fail_if_not_passed:" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "actions/setup-java@v4" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "distribution: temurin" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent 'java-version: "17"' "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "chmod +x ./osmu-backend/gradlew" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "OSMU_KUBECONFIG_BASE64" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "Plan IAM/RBAC finalizer" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "Run IAM/RBAC finalizer" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "./scripts/finalize-iam-rbac-readiness.ps1" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "-PowerShellCommand" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "-GradleCommand" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "-RunBackendPolicyTests" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "-RunKubernetesLiveAuth" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "run_live=true is required when run_kubernetes_live_auth=true." "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "actions/upload-artifact@v4" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "iam-rbac-finalizer-" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent ".osmu-run/latest-iam-rbac-finalize.json" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent ".osmu-run/latest-storage-expansion-rbac-auth.json" "IAM/RBAC Finalizer CI workflow"
Assert-Contains $iamRbacWorkflowContent "osmu-backend/build/reports/tests/test/**" "IAM/RBAC Finalizer CI workflow"

$storageExpansionWorkflow = Read-Workflow $StorageExpansionFinalizerWorkflowPath "Storage Expansion Finalizer CI workflow"
$storageExpansionWorkflowContent = $storageExpansionWorkflow.Content

Assert-Contains $storageExpansionWorkflowContent "name: Storage Expansion Finalizer CI" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "workflow_dispatch:" "Storage Expansion Finalizer CI workflow"
Assert-NotContains $storageExpansionWorkflowContent "pull_request:" "Storage Expansion Finalizer CI workflow"
Assert-NotContains $storageExpansionWorkflowContent "push:" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "contents: read" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "runs-on: ubuntu-latest" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "timeout-minutes: 30" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "shell: pwsh" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "run_live:" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "default: false" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "confirm_apply:" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "OSMU_KUBECONFIG_BASE64" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "OSMU_ADMIN_PASSWORD" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "Plan storage expansion finalizer" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "./scripts/finalize-storage-expansion.ps1" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "-PlanOnly" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "-PowerShellCommand" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "Prepare kubeconfig" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "Run storage expansion finalizer" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent 'if ("${{ inputs.run_backend_apply }}" -eq "true")' "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "confirm_apply=true is required when run_backend_apply=true." "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "-ConfirmApply" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "actions/upload-artifact@v4" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent "storage-expansion-finalizer-" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent ".osmu-run/latest-storage-expansion-finalize.json" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent ".osmu-run/latest-storage-expansion-rbac-auth.json" "Storage Expansion Finalizer CI workflow"
Assert-Contains $storageExpansionWorkflowContent ".osmu-run/latest-storage-expansion-server-dry-run.json" "Storage Expansion Finalizer CI workflow"

$kubernetesHaDrWorkflow = Read-Workflow $KubernetesHaDrReadinessWorkflowPath "Kubernetes HA DR Readiness CI workflow"
$kubernetesHaDrWorkflowContent = $kubernetesHaDrWorkflow.Content

Assert-Contains $kubernetesHaDrWorkflowContent "name: Kubernetes HA DR Readiness CI" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "workflow_dispatch:" "Kubernetes HA DR Readiness CI workflow"
Assert-NotContains $kubernetesHaDrWorkflowContent "pull_request:" "Kubernetes HA DR Readiness CI workflow"
Assert-NotContains $kubernetesHaDrWorkflowContent "push:" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "contents: read" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "runs-on: ubuntu-latest" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "timeout-minutes: 25" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "run_live:" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "restore_manifest_path:" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "OSMU_KUBECONFIG_BASE64" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "Plan Kubernetes HA DR readiness" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "./scripts/verify-kubernetes-ha-dr-readiness.ps1" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "-PlanOnly" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "Prepare kubeconfig" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "Check kubectl client" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "Run Kubernetes HA DR readiness" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "actions/upload-artifact@v4" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent "kubernetes-ha-dr-readiness-" "Kubernetes HA DR Readiness CI workflow"
Assert-Contains $kubernetesHaDrWorkflowContent ".osmu-run/latest-kubernetes-ha-dr-readiness.json" "Kubernetes HA DR Readiness CI workflow"

$kubernetesDrWorkflow = Read-Workflow $KubernetesDrFinalizerWorkflowPath "Kubernetes DR Finalizer CI workflow"
$kubernetesDrWorkflowContent = $kubernetesDrWorkflow.Content

Assert-Contains $kubernetesDrWorkflowContent "name: Kubernetes DR Finalizer CI" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "workflow_dispatch:" "Kubernetes DR Finalizer CI workflow"
Assert-NotContains $kubernetesDrWorkflowContent "pull_request:" "Kubernetes DR Finalizer CI workflow"
Assert-NotContains $kubernetesDrWorkflowContent "push:" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "contents: read" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "runs-on: ubuntu-latest" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "timeout-minutes: 45" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "shell: pwsh" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "run_live:" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "server_dry_run_only:" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "confirm_restore:" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "submit_evidence:" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "OSMU_KUBECONFIG_BASE64" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "OSMU_ADMIN_PASSWORD" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "Plan Kubernetes DR finalizer" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "./scripts/finalize-kubernetes-dr-drill.ps1" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "-PlanOnly" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "-PowerShellCommand" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "Prepare kubeconfig" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "Run Kubernetes DR finalizer" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "backup_timestamp must be set to a real timestamp when run_live=true." "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "Use either server_dry_run_only=true or confirm_restore=true, not both." "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "Use server_dry_run_only=true or confirm_restore=true when run_live=true." "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "confirm_restore=true is required when submit_evidence=true." "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "OSMU_ADMIN_PASSWORD secret is required for confirmed restore smoke." "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "-ServerDryRunOnly" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "-ConfirmRestore" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "-SubmitEvidence" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "actions/upload-artifact@v4" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent "kubernetes-dr-finalizer-" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent ".osmu-run/latest-kubernetes-dr-finalize.json" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent ".osmu-run/latest-kubernetes-dr-finalize.md" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent ".osmu-run/latest-kubernetes-dr-drill.json" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent ".osmu-run/latest-kubernetes-restore-smoke.json" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent ".osmu-run/latest-kubernetes-dr-evidence-request.json" "Kubernetes DR Finalizer CI workflow"
Assert-Contains $kubernetesDrWorkflowContent ".osmu-run/latest-kubernetes-backup-artifact-transfer.json" "Kubernetes DR Finalizer CI workflow"

$kubernetesOperationsReportSyncWorkflow = Read-Workflow $KubernetesOperationsReportSyncWorkflowPath "Kubernetes Operations Report Sync CI workflow"
$kubernetesOperationsReportSyncWorkflowContent = $kubernetesOperationsReportSyncWorkflow.Content

Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "name: Kubernetes Operations Report Sync CI" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "workflow_dispatch:" "Kubernetes Operations Report Sync CI workflow"
Assert-NotContains $kubernetesOperationsReportSyncWorkflowContent "pull_request:" "Kubernetes Operations Report Sync CI workflow"
Assert-NotContains $kubernetesOperationsReportSyncWorkflowContent "push:" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "contents: read" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "runs-on: ubuntu-latest" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "timeout-minutes: 20" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "namespace:" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "report_path:" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "run_live:" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "apply:" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "OSMU_KUBECONFIG_BASE64" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Validate dispatch inputs" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "run_live=true is required when apply=true." "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Write operations readiness convergence report" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "./scripts/write-operations-readiness-convergence.ps1" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Plan Kubernetes operations report sync" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "./scripts/sync-kubernetes-operations-reports.ps1" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "-PlanOnly" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Prepare kubeconfig" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Check kubectl client" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Server dry-run Kubernetes operations report sync" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "-ServerDryRunOnly" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "Apply Kubernetes operations report sync" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "-Apply" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "actions/upload-artifact@v4" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent "kubernetes-operations-report-sync-" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent ".osmu-run/latest-operations-readiness-convergence.json" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent ".osmu-run/latest-kubernetes-operations-report-sync-plan.json" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent ".osmu-run/latest-kubernetes-operations-report-sync-server-dry-run.json" "Kubernetes Operations Report Sync CI workflow"
Assert-Contains $kubernetesOperationsReportSyncWorkflowContent ".osmu-run/latest-kubernetes-operations-report-sync.json" "Kubernetes Operations Report Sync CI workflow"

$operationsReadinessWorkflow = Read-Workflow $OperationsReadinessFinalizerWorkflowPath "Operations Readiness Finalizer CI workflow"
$operationsReadinessWorkflowContent = $operationsReadinessWorkflow.Content

Assert-Contains $operationsReadinessWorkflowContent "name: Operations Readiness Finalizer CI" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "workflow_dispatch:" "Operations Readiness Finalizer CI workflow"
Assert-NotContains $operationsReadinessWorkflowContent "pull_request:" "Operations Readiness Finalizer CI workflow"
Assert-NotContains $operationsReadinessWorkflowContent "push:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "contents: read" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "runs-on: ubuntu-latest" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "timeout-minutes: 60" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "shell: pwsh" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_live:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_storage_expansion_finalizer:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_ha_dr_readiness:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_kubernetes_dr_finalizer:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_iam_rbac_finalizer:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_iam_kubernetes_live_auth:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_security_evidence_finalizer:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "server_dry_run_only:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "confirm_restore:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "fail_if_not_ready:" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "OSMU_KUBECONFIG_BASE64" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "OSMU_ADMIN_PASSWORD" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "Plan operations readiness finalizer" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "./scripts/finalize-operations-readiness.ps1" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "-PlanOnly" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "-PowerShellCommand" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "Prepare kubeconfig" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "Run operations readiness finalizer" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "backup_timestamp must be set to a real timestamp when run_kubernetes_dr_finalizer=true." "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "run_iam_rbac_finalizer=true is required when run_iam_kubernetes_live_auth=true." "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "Use either server_dry_run_only=true or confirm_restore=true, not both." "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "OSMU_ADMIN_PASSWORD secret is required when confirm_restore=true." "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "actions/upload-artifact@v4" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent "operations-readiness-finalizer-" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-operations-readiness-finalize.json" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-operations-readiness.json" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-storage-expansion-finalize.json" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-kubernetes-ha-dr-readiness.json" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-kubernetes-dr-finalize.json" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-iam-rbac-finalize.json" "Operations Readiness Finalizer CI workflow"
Assert-Contains $operationsReadinessWorkflowContent ".osmu-run/latest-security-evidence-finalize.json" "Operations Readiness Finalizer CI workflow"

$operationsReadinessArtifactWorkflow = Read-Workflow $OperationsReadinessArtifactFinalizerWorkflowPath "Operations Readiness Artifact Finalizer CI workflow"
$operationsReadinessArtifactWorkflowContent = $operationsReadinessArtifactWorkflow.Content

Assert-Contains $operationsReadinessArtifactWorkflowContent "name: Operations Readiness Artifact Finalizer CI" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "workflow_dispatch:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-NotContains $operationsReadinessArtifactWorkflowContent "pull_request:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-NotContains $operationsReadinessArtifactWorkflowContent "push:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "contents: read" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "actions: read" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "runs-on: ubuntu-latest" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "timeout-minutes: 30" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "storage_expansion_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "ha_dr_readiness_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "kubernetes_dr_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "iam_rbac_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "security_evidence_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "secret_rotation_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "secret_rotation_artifact_name:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "commercial_integration_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "commercial_integration_artifact_name:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "commercial_approval_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "commercial_approval_artifact_name:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "enterprise_auth_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "operations_handoff_package_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "operations_handoff_package_artifact_name:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "kubernetes_operations_report_sync_run_id:" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download secret rotation evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download commercial integration evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download commercial approval evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download enterprise auth smoke evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download operations handoff package evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download Kubernetes operations report sync evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "SecretRotationArtifactPath" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "CommercialIntegrationArtifactPath" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "CommercialApprovalArtifactPath" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "EnterpriseAuthArtifactPath" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "OperationsHandoffPackageArtifactPath" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "KubernetesOperationsReportSyncArtifactPath" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-secret-rotation-evidence.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-secret-rotation-evidence.md" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-commercial-integration-evidence.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-commercial-integration-evidence.md" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-commercial-approval-evidence.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-commercial-approval-evidence.md" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-enterprise-auth-smoke.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-operations-handoff-package.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-operations-handoff-package.md" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-kubernetes-operations-report-sync.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "actions/download-artifact@v4" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "github-token: `${{ secrets.GITHUB_TOKEN }}" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download storage expansion evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download Kubernetes HA DR readiness evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download Kubernetes DR finalizer evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download IAM RBAC finalizer evidence" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Download security evidence finalizer artifact" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Import downloaded evidence artifacts" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "./scripts/import-operations-readiness-artifacts.ps1" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "Write operations readiness report" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "./scripts/write-operations-readiness.ps1" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "-FailIfNotReady" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "actions/upload-artifact@v4" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent "operations-readiness-artifacts-" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-operations-readiness-artifact-import.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-operations-readiness.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-storage-expansion-finalize.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-kubernetes-ha-dr-readiness.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-kubernetes-dr-finalize.json" "Operations Readiness Artifact Finalizer CI workflow"
Assert-Contains $operationsReadinessArtifactWorkflowContent ".osmu-run/latest-security-evidence-finalize.json" "Operations Readiness Artifact Finalizer CI workflow"

$manualSecretRotationWorkflow = Read-Workflow $ManualSecretRotationEvidenceWorkflowPath "Manual Secret Rotation Evidence workflow"
$manualSecretRotationWorkflowContent = $manualSecretRotationWorkflow.Content

Assert-Contains $manualSecretRotationWorkflowContent "name: Manual Secret Rotation Evidence" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "workflow_dispatch:" "Manual Secret Rotation Evidence workflow"
Assert-NotContains $manualSecretRotationWorkflowContent "pull_request:" "Manual Secret Rotation Evidence workflow"
Assert-NotContains $manualSecretRotationWorkflowContent "push:" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "contents: read" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "runs-on: ubuntu-latest" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "timeout-minutes: 15" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "Record secret rotation evidence" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "./scripts/write-secret-rotation-evidence.ps1" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "-FailIfNotPassed" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "actions/upload-artifact@v4" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent "secret-rotation-evidence-" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent ".osmu-run/latest-secret-rotation-evidence.json" "Manual Secret Rotation Evidence workflow"
Assert-Contains $manualSecretRotationWorkflowContent ".osmu-run/latest-secret-rotation-evidence.md" "Manual Secret Rotation Evidence workflow"

$manualCommercialIntegrationWorkflow = Read-Workflow $ManualCommercialIntegrationEvidenceWorkflowPath "Manual Commercial Integration Evidence workflow"
$manualCommercialIntegrationWorkflowContent = $manualCommercialIntegrationWorkflow.Content

Assert-Contains $manualCommercialIntegrationWorkflowContent "name: Manual Commercial Integration Evidence" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "workflow_dispatch:" "Manual Commercial Integration Evidence workflow"
Assert-NotContains $manualCommercialIntegrationWorkflowContent "pull_request:" "Manual Commercial Integration Evidence workflow"
Assert-NotContains $manualCommercialIntegrationWorkflowContent "push:" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "contents: read" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "runs-on: ubuntu-latest" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "timeout-minutes: 15" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "Record commercial integration evidence" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "./scripts/write-commercial-integration-evidence.ps1" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "-RequireAllImplementedAdapters" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "-FailIfNotPassed" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "actions/upload-artifact@v4" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent "commercial-integration-evidence-" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent ".osmu-run/latest-commercial-integration-evidence.json" "Manual Commercial Integration Evidence workflow"
Assert-Contains $manualCommercialIntegrationWorkflowContent ".osmu-run/latest-commercial-integration-evidence.md" "Manual Commercial Integration Evidence workflow"

$manualCommercialApprovalWorkflow = Read-Workflow $ManualCommercialApprovalEvidenceWorkflowPath "Manual Commercial Approval Evidence workflow"
$manualCommercialApprovalWorkflowContent = $manualCommercialApprovalWorkflow.Content

Assert-Contains $manualCommercialApprovalWorkflowContent "name: Manual Commercial Approval Evidence" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "workflow_dispatch:" "Manual Commercial Approval Evidence workflow"
Assert-NotContains $manualCommercialApprovalWorkflowContent "pull_request:" "Manual Commercial Approval Evidence workflow"
Assert-NotContains $manualCommercialApprovalWorkflowContent "push:" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "contents: read" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "runs-on: ubuntu-latest" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "timeout-minutes: 15" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "Record commercial approval evidence" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "./scripts/write-commercial-approval-evidence.ps1" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "-FailIfNotPassed" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "actions/upload-artifact@v4" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent "commercial-approval-evidence-" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent ".osmu-run/latest-commercial-approval-evidence.json" "Manual Commercial Approval Evidence workflow"
Assert-Contains $manualCommercialApprovalWorkflowContent ".osmu-run/latest-commercial-approval-evidence.md" "Manual Commercial Approval Evidence workflow"

$manualOperationsHandoffPackageWorkflow = Read-Workflow $ManualOperationsHandoffPackageWorkflowPath "Manual Operations Handoff Package workflow"
$manualOperationsHandoffPackageWorkflowContent = $manualOperationsHandoffPackageWorkflow.Content

Assert-Contains $manualOperationsHandoffPackageWorkflowContent "name: Manual Operations Handoff Package" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "workflow_dispatch:" "Manual Operations Handoff Package workflow"
Assert-NotContains $manualOperationsHandoffPackageWorkflowContent "pull_request:" "Manual Operations Handoff Package workflow"
Assert-NotContains $manualOperationsHandoffPackageWorkflowContent "push:" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "contents: read" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "runs-on: ubuntu-latest" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "timeout-minutes: 15" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "Record operations handoff package" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "./scripts/write-operations-handoff-package.ps1" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "-RequireProductionEvidence" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "-FailIfNotPassed" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "actions/upload-artifact@v4" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent "operations-handoff-package-" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent ".osmu-run/latest-operations-handoff-package.json" "Manual Operations Handoff Package workflow"
Assert-Contains $manualOperationsHandoffPackageWorkflowContent ".osmu-run/latest-operations-handoff-package.md" "Manual Operations Handoff Package workflow"

$enterpriseAuthSmokeWorkflow = Read-Workflow $EnterpriseAuthSmokeWorkflowPath "Enterprise Auth Smoke CI workflow"
$enterpriseAuthSmokeWorkflowContent = $enterpriseAuthSmokeWorkflow.Content

Assert-Contains $enterpriseAuthSmokeWorkflowContent "name: Enterprise Auth Smoke CI" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "workflow_dispatch:" "Enterprise Auth Smoke CI workflow"
Assert-NotContains $enterpriseAuthSmokeWorkflowContent "pull_request:" "Enterprise Auth Smoke CI workflow"
Assert-NotContains $enterpriseAuthSmokeWorkflowContent "push:" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "contents: read" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "runs-on: ubuntu-latest" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "timeout-minutes: 20" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "run_live:" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "require_oidc:" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "require_ldap:" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "confirm_jit_provision:" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "Plan enterprise auth smoke" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "Run enterprise auth smoke" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "Promote plan-only enterprise auth smoke" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "./scripts/write-enterprise-auth-smoke-plan.ps1" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "OSMU_ENTERPRISE_AUTH_ADMIN_PASSWORD" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "OSMU_ENTERPRISE_AUTH_LDAP_LOGIN_ID" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "OSMU_ENTERPRISE_AUTH_LDAP_PASSWORD" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "OSMU_ENTERPRISE_AUTH_CLAIM_PREVIEW_JSON_BASE64" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "OSMU_ENTERPRISE_AUTH_JIT_PROVISION_JSON_BASE64" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "OSMU_ENTERPRISE_AUTH_ADMIN_PASSWORD secret is required when run_live=true." "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "actions/upload-artifact@v4" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent "enterprise-auth-smoke-" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent ".osmu-run/latest-enterprise-auth-smoke.json" "Enterprise Auth Smoke CI workflow"
Assert-Contains $enterpriseAuthSmokeWorkflowContent ".osmu-run/latest-enterprise-auth-smoke.md" "Enterprise Auth Smoke CI workflow"

$frontendPackage = Read-RequiredFile $FrontendPackagePath "Frontend package manifest"
$frontendPackageJson = $frontendPackage.Content | ConvertFrom-Json
if ($frontendPackageJson.scripts.'test:e2e' -ne "playwright test ./e2e/lightweight-demo.spec.js --browser=chromium --reporter=line") {
    throw "Frontend package manifest test:e2e script does not match Browser E2E workflow contract."
}
if (-not $frontendPackageJson.devDependencies.'@playwright/test') {
    throw "Frontend package manifest must include @playwright/test devDependency for Browser E2E."
}

$playwrightConfig = Read-RequiredFile $PlaywrightConfigPath "Playwright config"
$playwrightConfigContent = $playwrightConfig.Content
Assert-Contains $playwrightConfigContent "OSMU_PLAYWRIGHT_CHANNEL" "Playwright config"
Assert-Contains $playwrightConfigContent "channel: browserChannel || undefined" "Playwright config"

$browserSpec = Read-RequiredFile $BrowserE2ESpecPath "Browser E2E spec"
$browserSpecContent = $browserSpec.Content

Assert-Contains $browserSpecContent "admin can complete lightweight storage portal click path" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer login lands on S3 API console with access key controls" "Browser E2E spec"
Assert-Contains $browserSpecContent "org admin can open scoped admin page without global operation panels" "Browser E2E spec"
Assert-Contains $browserSpecContent "user is redirected away from admin page" "Browser E2E spec"
Assert-Contains $browserSpecContent "ORG_ADMIN" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-role-empty-state" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-role-restricted-panel-list" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-share-policy-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-share-analytics-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "quota-policy-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent ".lifecycle-rules" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-expansion-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-storage-profile-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "toHaveURL(/\/developer$/)" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin action failures show remediation guidance" "Browser E2E spec"
Assert-Contains $browserSpecContent "adminActionFailures" "Browser E2E spec"
Assert-Contains $browserSpecContent "AUTHENTICATION_REQUIRED" "Browser E2E spec"
Assert-Contains $browserSpecContent "AUTHORIZATION_FAILED" "Browser E2E spec"
Assert-Contains $browserSpecContent "VALIDATION_ERROR" "Browser E2E spec"
Assert-Contains $browserSpecContent "NOT_FOUND" "Browser E2E spec"
Assert-Contains $browserSpecContent "STATE_CONFLICT" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-action-remediation-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-action-remediation-code" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-action-remediation-detail" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-action-remediation-steps" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-action-remediation-primary" "Browser E2E spec"
Assert-Contains $browserSpecContent 'Request ID ${requestId}' "Browser E2E spec"
Assert-Contains $browserSpecContent "login-submit-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "login-mode-developer" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer-page" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer-s3-endpoint-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer-client-snippets-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-create-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-scope-add-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-scope-remove-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-list" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-delete-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer can filter access keys and inspect operational hints" "Browser E2E spec"
Assert-Contains $browserSpecContent "expired-browser-key" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-filter-expired" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-filter-expiring" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-filter-unused" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-filter-inactive" "Browser E2E spec"
Assert-Contains $browserSpecContent "Disable expired" "Browser E2E spec"
Assert-Contains $browserSpecContent "Rotate soon" "Browser E2E spec"
Assert-Contains $browserSpecContent "Review unused" "Browser E2E spec"
Assert-Contains $browserSpecContent "Review stale" "Browser E2E spec"
Assert-Contains $browserSpecContent "3 selected / 3 cleanup candidates" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer can export and confirm access key bulk cleanup" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-cleanup-candidate-checkbox" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-cleanup-export-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "osmu.access-key-cleanup-preview.v1" "Browser E2E spec"
Assert-Contains $browserSpecContent "selectedCandidateIds" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer-e2e-super-secret" "Browser E2E spec"
Assert-Contains $browserSpecContent "access-key-cleanup-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "Access Key Bulk Cleanup" "Browser E2E spec"
Assert-Contains $browserSpecContent "toBeDisabled()" "Browser E2E spec"
Assert-Contains $browserSpecContent "INACTIVE" "Browser E2E spec"
Assert-Contains $browserSpecContent "confirm-dialog" "Browser E2E spec"
Assert-Contains $browserSpecContent "confirm-cancel-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "confirm-submit-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "not.toContainText" "Browser E2E spec"
Assert-Contains $browserSpecContent "deleteBucketRow).toHaveCount(0)" "Browser E2E spec"
Assert-Contains $browserSpecContent "버킷 삭제 완료" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-access-keys" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-security-audit-policy-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-security-policy-metrics" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-security-policy-row" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-security-audit-open-audit-link" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-filter-form" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-lifecycle-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-lifecycle-load-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-lifecycle-save-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-lifecycle-delete-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-lifecycle-textarea" "Browser E2E spec"
Assert-Contains $browserSpecContent "Browser lifecycle" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-lifecycle-saved-count" "Browser E2E spec"
Assert-Contains $browserSpecContent "e2e/raw/" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-tags-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-tags-load-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-tags-save-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-tags-delete-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-tags-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket tags 저장 완료" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket tags 삭제 완료" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-create-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-row-name" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-row-usage" "Browser E2E spec"
Assert-Contains $browserSpecContent "bucket-row-object-count" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-profile-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-profile-select" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-profile-reason-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-profile-request-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-profile-request-row" "Browser E2E spec"
Assert-Contains $browserSpecContent "Storage profile requested" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-workflow-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-workflow-metrics" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-workflow-list" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-profile-approve-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-profile-reject-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-profile-apply-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "storage-expansion-create-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-expansion-approve-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-expansion-plan-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-expansion-apply-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-approval-expansion-reject-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "Storage expansion dry-run ready" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-storage-profile-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-storage-profile-request-row" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-storage-profile-approve-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "admin-storage-profile-apply-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "Storage profile request APPROVED" "Browser E2E spec"
Assert-Contains $browserSpecContent "Storage profile applied" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-key-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-file-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-upload-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-table" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-prefix-breadcrumb" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-prefix-breadcrumb-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-prefix-row" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-prefix-open-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "filter({ hasText: '/' }).click()" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-search-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-key-match" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-detail-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-detail-panel" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-metadata-row-state" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-tag-filter-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-tag-edit-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-tag-key-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "object-tag-save-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "project=archive" "Browser E2E spec"
Assert-Contains $browserSpecContent "stage=curated" "Browser E2E spec"
Assert-Contains $browserSpecContent "error-alert" "Browser E2E spec"
Assert-Contains $browserSpecContent "Tag keys can contain" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-search-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-result-select" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-limit-input" "Browser E2E spec"
Assert-Contains $browserSpecContent "toHaveCount(5)" "Browser E2E spec"
Assert-Contains $browserSpecContent "auditNextButton.click()" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-entry').nth(5)" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-export-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "osmu-audit.csv" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-reset-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "audit-next-button" "Browser E2E spec"
Assert-Contains $browserSpecContent "stale saved session returns to login redirect" "Browser E2E spec"
Assert-Contains $browserSpecContent "stored developer session opens developer console without login" "Browser E2E spec"
Assert-Contains $browserSpecContent "developer-stored-access" "Browser E2E spec"
Assert-Contains $browserSpecContent "login-form')).toHaveCount(0)" "Browser E2E spec"
Assert-Contains $browserSpecContent "redirect=(%2F|\/)dashboard" "Browser E2E spec"

Write-Host "CI workflows verified."
Write-Host "Lightweight workflow: $($lightweightWorkflow.Path)"
Write-Host "Durable Docker workflow: $($durableWorkflow.Path)"
Write-Host "Real S3 client workflow: $($realS3Workflow.Path)"
Write-Host "Container security workflow: $($containerSecurityWorkflow.Path)"
Write-Host "Security Evidence Finalizer workflow: $($securityEvidenceFinalizerWorkflow.Path)"
Write-Host "Browser E2E workflow: $($browserWorkflow.Path)"
Write-Host "IAM/RBAC Finalizer workflow: $($iamRbacWorkflow.Path)"
Write-Host "Storage Expansion Finalizer workflow: $($storageExpansionWorkflow.Path)"
Write-Host "Kubernetes HA DR Readiness workflow: $($kubernetesHaDrWorkflow.Path)"
Write-Host "Kubernetes DR Finalizer workflow: $($kubernetesDrWorkflow.Path)"
Write-Host "Kubernetes Operations Report Sync workflow: $($kubernetesOperationsReportSyncWorkflow.Path)"
Write-Host "Operations Readiness Finalizer workflow: $($operationsReadinessWorkflow.Path)"
Write-Host "Operations Readiness Artifact Finalizer workflow: $($operationsReadinessArtifactWorkflow.Path)"
Write-Host "Manual Secret Rotation Evidence workflow: $($manualSecretRotationWorkflow.Path)"
Write-Host "Manual Commercial Integration Evidence workflow: $($manualCommercialIntegrationWorkflow.Path)"
Write-Host "Manual Commercial Approval Evidence workflow: $($manualCommercialApprovalWorkflow.Path)"
Write-Host "Manual Operations Handoff Package workflow: $($manualOperationsHandoffPackageWorkflow.Path)"
Write-Host "Enterprise Auth Smoke workflow: $($enterpriseAuthSmokeWorkflow.Path)"
Write-Host "Playwright config: $($playwrightConfig.Path)"
Write-Host "Browser E2E spec: $($browserSpec.Path)"
