apiVersion: v1
kind: Service
metadata:
  name: osmu-frontend
  namespace: {{ include "osmu.namespace" . }}
  labels:
    app.kubernetes.io/name: osmu-frontend
    {{- include "osmu.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: osmu-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmu-frontend
  namespace: {{ include "osmu.namespace" . }}
  labels:
    app.kubernetes.io/name: osmu-frontend
    {{- include "osmu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: osmu-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: osmu-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: osmu
    spec:
      securityContext:
{{ toYaml .Values.frontend.podSecurityContext | indent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          securityContext:
{{ toYaml .Values.frontend.containerSecurityContext | indent 12 }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}

