{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osmu.secretName" . }}
  namespace: {{ include "osmu.namespace" . }}
  labels:
    {{- include "osmu.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_USER: {{ .Values.secrets.values.mariadbUser | quote }}
  MARIADB_PASSWORD: {{ .Values.secrets.values.mariadbPassword | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.values.mariadbRootPassword | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.values.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.values.minioRootPassword | quote }}
  OSMU_ADMIN_PASSWORD: {{ .Values.secrets.values.adminPassword | quote }}
  OSMU_JWT_SECRET: {{ .Values.secrets.values.jwtSecret | quote }}
  OSMU_ACCESS_KEY_SECRET_ENCRYPTION_KEY: {{ .Values.secrets.values.accessKeySecretEncryptionKey | quote }}
{{- end }}

