apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-backend
  namespace: {{ include "osmu.namespace" . }}
  labels:
    app.kubernetes.io/name: osmu-backend
    {{- include "osmu.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-frontend
  namespace: {{ include "osmu.namespace" . }}
  labels:
    app.kubernetes.io/name: osmu-frontend
    {{- include "osmu.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-mariadb
  namespace: {{ include "osmu.namespace" . }}
  labels:
    app.kubernetes.io/name: osmu-mariadb
    {{- include "osmu.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osmu-minio
  namespace: {{ include "osmu.namespace" . }}
  labels:
    app.kubernetes.io/name: osmu-minio
    {{- include "osmu.labels" . | nindent 4 }}
automountServiceAccountToken: false
