CREATE TABLE IF NOT EXISTS chargeback_notification_deliveries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    organization_name VARCHAR(255) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    estimated_total_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    warning_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
    critical_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
    channel VARCHAR(32) NOT NULL,
    target VARCHAR(512) NOT NULL,
    status VARCHAR(64) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NULL,
    subject VARCHAR(512) NOT NULL,
    message TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    requested_by VARCHAR(128) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(512) NULL,
    INDEX idx_chargeback_notification_deliveries_org_created (organization_id, created_at),
    INDEX idx_chargeback_notification_deliveries_status_next (status, next_attempt_at)
);
