CREATE TABLE IF NOT EXISTS chargeback_invoice_drafts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    organization_id BIGINT NOT NULL,
    organization_name VARCHAR(255) NOT NULL,
    currency VARCHAR(12) NOT NULL,
    window_from TIMESTAMP NULL,
    window_to TIMESTAMP NULL,
    preview_generated_at TIMESTAMP NOT NULL,
    event_scan_limit INT NOT NULL,
    storage_gb_month_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    ingress_gb_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    egress_gb_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    internal_gb_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    operation_thousand_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    bucket_count BIGINT NOT NULL DEFAULT 0,
    object_count BIGINT NOT NULL DEFAULT 0,
    used_bytes BIGINT NOT NULL DEFAULT 0,
    storage_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    traffic_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    operation_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    estimated_total_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    requested_by VARCHAR(128) NOT NULL,
    approved_by VARCHAR(128) NULL,
    reason VARCHAR(512) NOT NULL,
    approval_note VARCHAR(512) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP NULL,
    note VARCHAR(512) NOT NULL,
    INDEX idx_chargeback_invoice_drafts_status_created (status, created_at),
    INDEX idx_chargeback_invoice_drafts_org_created (organization_id, created_at)
);
