CREATE TABLE IF NOT EXISTS chargeback_final_invoices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_draft_id BIGINT NOT NULL,
    invoice_number VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payment_status VARCHAR(32) NOT NULL,
    organization_id BIGINT NOT NULL,
    organization_name VARCHAR(255) NOT NULL,
    currency VARCHAR(12) NOT NULL,
    window_from TIMESTAMP NULL,
    window_to TIMESTAMP NULL,
    preview_generated_at TIMESTAMP NOT NULL,
    event_scan_limit INT NOT NULL,
    storage_gb_month_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    ingress_gb_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    egress_gb_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    internal_gb_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    operation_thousand_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
    bucket_count BIGINT NOT NULL DEFAULT 0,
    object_count BIGINT NOT NULL DEFAULT 0,
    used_bytes BIGINT NOT NULL DEFAULT 0,
    storage_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    traffic_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    operation_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    estimated_total_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    requested_by VARCHAR(128) NOT NULL,
    approved_by VARCHAR(128) NOT NULL,
    finalized_by VARCHAR(128) NOT NULL,
    payment_requested_by VARCHAR(128) NULL,
    payment_recorded_by VARCHAR(128) NULL,
    reason VARCHAR(512) NOT NULL,
    approval_note VARCHAR(512) NULL,
    finalization_note VARCHAR(512) NOT NULL,
    payment_request_note VARCHAR(512) NULL,
    payment_reference VARCHAR(512) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP NULL,
    finalized_at TIMESTAMP NOT NULL,
    payment_requested_at TIMESTAMP NULL,
    paid_at TIMESTAMP NULL,
    note VARCHAR(512) NOT NULL,
    UNIQUE KEY uk_chargeback_final_invoices_source_draft (source_draft_id),
    INDEX idx_chargeback_final_invoices_status_created (status, created_at),
    INDEX idx_chargeback_final_invoices_payment_status (payment_status, updated_at),
    INDEX idx_chargeback_final_invoices_org_created (organization_id, created_at)
);
