CREATE TABLE IF NOT EXISTS data_flow_monthly_rollups (
    rollup_month DATE NOT NULL,
    bucket_name VARCHAR(255) NOT NULL,
    actor_id VARCHAR(255) NOT NULL DEFAULT '',
    source VARCHAR(64) NOT NULL,
    operation VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT '',
    success_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    cancel_count BIGINT NOT NULL DEFAULT 0,
    total_count BIGINT NOT NULL DEFAULT 0,
    uploaded_bytes BIGINT NOT NULL DEFAULT 0,
    downloaded_bytes BIGINT NOT NULL DEFAULT 0,
    copied_bytes BIGINT NOT NULL DEFAULT 0,
    total_bytes BIGINT NOT NULL DEFAULT 0,
    refreshed_at TIMESTAMP NOT NULL,
    PRIMARY KEY (rollup_month, bucket_name, actor_id, source, operation, status),
    KEY idx_data_flow_monthly_rollups_bucket (bucket_name, rollup_month),
    KEY idx_data_flow_monthly_rollups_actor (actor_id, rollup_month),
    KEY idx_data_flow_monthly_rollups_operation (operation, rollup_month),
    KEY idx_data_flow_monthly_rollups_status (status, rollup_month),
    KEY idx_data_flow_monthly_rollups_refreshed_at (refreshed_at)
);
